spring.application.name=ebank-bot
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-4o
spring.cloud.config.discovery.enabled=true
spring.cloud.config.enabled=false
server.port=8058
spring.ai.mcp.client.streamable-http.connections.customer.url=http://localhost:8056/mcp
spring.ai.mcp.client.streamable-http.connections.ebank.url=http://localhost:8057/mcp

discord.token=

telegram.token=
telegram.username=${TELEGRAM_BOT_USERNAME:EbankBot}
telegrambots.enabled=false
logging.level.net.example.ebankbot.telegram=DEBUG
logging.level.org.telegram.telegrambots=INFO
eureka.client.enabled=false
spring.cloud.discovery.enabled=false


